package com.maxmauroner.zenguard

import android.content.Context
import android.content.SharedPreferences

/** Fixed, local-only categories for completed guard interventions. */
internal enum class EnforcementReason(val key: String) {
  YOUTUBE_SHORTS("youtube_shorts"),
  INSTAGRAM_REELS("instagram_reels"),
  INSTAGRAM_HOME("instagram_home"),
  INSTAGRAM_EXPLORE("instagram_explore"),
  X_HOME("x_home"),
  X_VIDEOS("x_videos"),
  BLOCKED_SITE("blocked_site"),
  APP_LIMIT("app_limit"),
  ROLLING_LIMIT("rolling_limit"),
  TIMED_VISIT("timed_visit"),
}

/** Only a completed enforcement action is eligible for the statistics ledger. */
internal enum class EnforcementStatsOutcome {
  SUCCESS,
  FAILED,
  OBSERVED,
}

internal data class EnforcementStatsSnapshot(
  val total: Long,
  val counts: Map<String, Long>,
  val lastEventAt: Long,
)

/**
 * Durable aggregate counters for successful interventions.
 *
 * The action key is generated by the service for one intervention. Repeated
 * accessibility events with the same key are ignored, while a new key records
 * another intervention. Only fixed reason keys, counters, and a timestamp are
 * persisted; no inspected screen content is included.
 */
internal class EnforcementStatsStore {
  private val preferences: SharedPreferences

  constructor(context: Context) : this(
    context.getSharedPreferences(FILE_NAME, Context.MODE_PRIVATE),
  )

  internal constructor(preferences: SharedPreferences) {
    this.preferences = preferences
  }

  @Synchronized
  fun record(reason: EnforcementReason, actionKey: String, nowMs: Long = System.currentTimeMillis()): Boolean {
    if (actionKey.isBlank()) return false

    return try {
      if (!ensureCurrentSchema()) return false
      val reasonActionKey = reasonActionKey(reason)
      val previousReasonAction = preferences.getString(reasonActionKey, null)
      if (previousReasonAction == actionKey ||
        (previousReasonAction == null && preferences.getString(KEY_LAST_ACTION, null) == actionKey)
      ) return false

      val total = readLong(KEY_TOTAL)
      val categoryTotal = readLong(reason.key)
      preferences.edit()
        .putLong(KEY_TOTAL, increment(total))
        .putLong(reason.key, increment(categoryTotal))
        .putString(KEY_LAST_ACTION, actionKey)
        .putString(reasonActionKey, actionKey)
        .putLong(KEY_LAST_EVENT_AT, nowMs.coerceAtLeast(0L))
        // Apply asynchronously so statistics can never hold up the service.
        .apply()
      true
    } catch (_: RuntimeException) {
      // SharedPreferences corruption or I/O is not an enforcement failure.
      false
    }
  }

  @Synchronized
  fun snapshot(): EnforcementStatsSnapshot {
    return try {
      if (!ensureCurrentSchema()) {
        EMPTY
      } else {
        val values = preferences.all
        EnforcementStatsSnapshot(
          total = readLong(values, KEY_TOTAL),
          counts = EnforcementReason.values().associate { it.key to readLong(values, it.key) },
          lastEventAt = readLong(values, KEY_LAST_EVENT_AT),
        )
      }
    } catch (_: RuntimeException) {
      EMPTY
    }
  }

  /**
   * A missing schema is the only legacy state: initialize it in place and keep
   * any valid aggregate keys. Future schemas are not safe to reinterpret or
   * reset, so they remain unreadable until code explicitly migrates them.
   */
  private fun ensureCurrentSchema(): Boolean {
    return when (readSchemaVersion()) {
      CURRENT_SCHEMA_VERSION -> true
      LEGACY_SCHEMA_VERSION -> {
        try {
          preferences.edit().putInt(KEY_SCHEMA_VERSION, CURRENT_SCHEMA_VERSION).apply()
        } catch (_: RuntimeException) {
          false
        }
        true
      }
      else -> false
    }
  }

  private fun readSchemaVersion(): Int = try {
    preferences.getInt(KEY_SCHEMA_VERSION, LEGACY_SCHEMA_VERSION)
  } catch (_: ClassCastException) {
    LEGACY_SCHEMA_VERSION
  }

  private fun readLong(key: String): Long = try {
    preferences.getLong(key, 0L).coerceAtLeast(0L)
  } catch (_: ClassCastException) {
    0L
  }

  private fun readLong(values: Map<String, *>, key: String): Long =
    (values[key] as? Long)?.coerceAtLeast(0L) ?: 0L

  private fun reasonActionKey(reason: EnforcementReason) = "${KEY_LAST_ACTION}_${reason.key}"

  private fun increment(value: Long): Long = if (value == Long.MAX_VALUE) value else value + 1L

  companion object {
    private const val FILE_NAME = "zen_guard_enforcement_stats"
    internal const val CURRENT_SCHEMA_VERSION = 1
    private const val LEGACY_SCHEMA_VERSION = 0
    private const val KEY_SCHEMA_VERSION = "schema_version"
    private const val KEY_TOTAL = "total"
    private const val KEY_LAST_ACTION = "last_action"
    private const val KEY_LAST_EVENT_AT = "last_event_at"
    private val EMPTY = EnforcementStatsSnapshot(
      total = 0L,
      counts = EnforcementReason.values().associate { it.key to 0L },
      lastEventAt = 0L,
    )
  }
}
